# Purchase
ARTICLE_MAX_LENGTH = 32
QUERY_MAX_LENGTH = 256
ORDER_ID_MAX_LENGTH = 256
PURCHASE_NAME_MAX_LENGTH = 256
TEXT_CHOICES_MAX_LENGTH = 36
SELLER_NAME_MAX_LENGTH = 256
SELLER_FULL_NAME_MAX_LENGTH = 256
SELLER_INN_MAX_LENGTH = 20

# MarketplaceProfile
PHONE_NUMBER_MAX_LENGTH = 32
PROFILE_NAME_MAX_LENGTH = 36
CARD_NUMBER_MAX_LENGTH = 96
DBS_CODE_MAX_LENGTH = 8

# Proxy
PROXY_NAME_MAX_LENGTH = 256

# Review
REVIEW_MAX_RATING = 5
REVIEW_MIN_RATING = 1
