# Purchase
ARTICLE_MAX_LENGTH = 32
QUERY_MAX_LENGTH = 256
ORDER_ID_MAX_LENGTH = 256
PURCHASE_NAME_MAX_LENGTH = 256
TEXT_CHOICES_MAX_LENGTH = 36
SELLER_NAME_MAX_LENGTH = 256
SELLER_FULL_NAME_MAX_LENGTH = 256
SELLER_INN_MAX_LENGTH = 20
